### ISSUE TITLE
Create locations

### ISSUE THREAD

**Issue by LauraBeatris** [vejovoce/shikoba-api#4]
## Description

Blocked by https://github.com/vertico/vertico-api/issues/1

Create locations table in locations context:

![image](https://user-images.githubusercontent.com/26944512/93835743-97a85580-fc56-11ea-92ed-6ad1dba5699a.png)

## Notes

- Add a nullable reference for users table. 

## Tasks

- [ ] Create location migration.
- [ ] Create location Ecto schema. 
- [ ] Add location as nested changeset in user schema (we can use [cast_assoc](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3)
- [ ] Create location context with [Crudry](https://hexdocs.pm/crudry) default functions 
- [ ] Create GraphQL schema (just the schema)
