### ISSUE TITLE
Create NGOs

### ISSUE THREAD

**Issue by LauraBeatris** [vejovoce/shikoba-api#6]
## Description 

Create NGOs table and context.

![image](https://user-images.githubusercontent.com/26944512/93835949-582e3900-fc57-11ea-94ac-bbe119aa318b.png)

## Notes

- Upload is not implemented yet. Use [Faker](https://hexdocs.pm/faker/api-reference.html) as workaround in `photo`.
- Save `cnpj` with only numbers.
- Ignore `location_id` and `social_network_id` for now.

## Tasks

- [ ] Create migration.
- [ ] Add `NGO` reference to locations table (a [belongs_to](https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3) association in location schema)
- [ ] Create `NGO` Ecto schema in `NGO` context. Use [Crudry](https://hexdocs.pm/crudry) here
- [ ] Add location nested changeset in NGO changeset. Use [cast_assoc](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3) like in https://github.com/vertico/vertico-api/issues/3 
- [ ] Create NGO GraphQL schema with all basic queries and mutations.
- [ ] Create factory.
- [ ] Create seeds. 
- [ ] Create tests.
